global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/node_alerts.yml"

scrape_configs:
  - job_name: 'midnight_node'
    static_configs:
      - targets: ['host.docker.internal:9615']

  - job_name: 'cardano_node'
    static_configs:
      # Default Cardano Node EKG/Prometheus metrics port is usually 12798
      - targets: ['host.docker.internal:12798']
